[package]
name = "resource"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

egui = "0.23.0"
eframe = "0.23.0"
systemstat = "0.2.3"
